"""updated product table and routers  

Revision ID: 944b72c992ec
Revises: 9e9b1ffd9c39
Create Date: 2025-11-26 18:55:45.141128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944b72c992ec'
down_revision: Union[str, None] = '9e9b1ffd9c39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_urls', sa.String(length=2500), nullable=True))
    op.drop_column('products', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('products', 'image_urls')
    # ### end Alembic commands ###
